# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField()),
                ('name', models.TextField()),
                ('object_type', models.TextField()),
                ('change_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('changer', models.TextField()),
                ('creator', models.TextField()),
                ('exdesc', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ScanEvent')),
            ],
        ),
    ]
