# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pidatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidatabase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pidatabase',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
