
export const API = 'http://localhost:8000';

export const ACTIONS = {
  FETCH_SCANS: 'FETCH_SCANS',
  FETCH_TAGS: 'FETCH_TAGS',
  FETCH_DATABASES: 'FETCH_DATABASES',
  TOGGLE_CREATE_ODBC: 'TOGGLE_CREATE_ODBC',
  TOGGLE_SCAN_ODBC: 'TOGGLE_SCAN_ODBC',
  TOGGLE_FILE_UPLOADER: 'TOGGLE_FILE_UPLOADER',
};
